# Generated by Django 5.2.11 on 2026-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('version_added', 'Version added'), ('access_granted', 'Access granted'), ('access_revoked', 'Access revoked'), ('access_expired', 'Access expired'), ('password_reset_request', 'Password reset request'), ('suspicious_activity', 'Suspicious activity')], max_length=50),
        ),
    ]
