# Generated by Django 5.2.11 on 2026-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccess',
            name='encrypted_dek',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
