# Generated by Django 5.2.11 on 2026-02-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentaccess_encrypted_dek'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved')], default='approved', max_length=10),
        ),
    ]
