# Generated by Django 5.2.11 on 2026-02-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
