# Generated by Django 5.2.11 on 2026-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_shared_with_document_size_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
