# Generated by Django 5.2.11 on 2026-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentaccess_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccess',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
