# Generated by Django 5.2.11 on 2026-02-23 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentaccess_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
