# Generated by Django 5.2.11 on 2026-02-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentaccess_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccess',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
