# Generated by Django 5.2.11 on 2026-02-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_key',
        ),
    ]
