# Generated by Django 5.2.11 on 2026-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Неудачные попытки входа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до'),
        ),
    ]
