# Generated by Django 5.2.11 on 2026-02-13 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Обновление'), ('DELETE', 'Удаление'), ('LOGIN', 'Вход'), ('LOGOUT', 'Выход'), ('SHARE', 'Предоставление доступа'), ('APPROVE', 'Подтверждение версии'), ('DOWNLOAD', 'Скачивание'), ('UPLOAD_VERSION', 'Загрузка новой версии')], max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['target_type'], name='audit_audit_target__3eb7a1_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx')],
            },
        ),
    ]
