# Generated by Django 5.2.11 on 2026-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_rename_extra_info_auditlog_new_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
