# Generated by Django 5.2.11 on 2026-04-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_target_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='target_name',
        ),
    ]
